### ISSUE TITLE
Support not having all varieties of FFTW installed

### ISSUE THREAD

**Issue by coderforlife** [pyFFTW/pyFFTW#70] opened 2015-10-16 01:15 UTC
In some Linux distributions it is common to have only the fftw3 library and not fftw3f. PyFFTW should detect that it is not available and work anyways (just not accept float32/single-precision inputs). Instead it just fails to import the whole module.

(If you are wondering why the whole devel package is not available, it is because we have numerous machines set up with mostly the same setup, but only one machine with devel, then we can use any machine with those libraries).

**Comment by rabernat** [comment] 2015-11-04 23:39
:+1: 

I found this to be quite a pain. To deal with it, in the [pyqg docs](http://pyqg.readthedocs.org/en/stable/installation.html#the-hard-way-installing-from-source) we recommend building FFTW three separate times. This is the only way to make pyfftw happy.

**Comment by hgomersall** [comment] 2015-11-05 10:08
Three separate times? How did that work?

**Comment by rabernat** [comment] 2015-11-05 13:10
The only way to get all three different FFTW datatypes required for pyfftw is to do
```bash
$ ./configure --enable-threads --enable-shared
$ make
$ sudo make install
$ ./configure --enable-threads --enable-shared --enable-float
$ make
$ sudo make install
$ ./configure --enable-threads --enable-shared --enable-long-double
$ make
$ sudo make install
```

**Comment by hgomersall** [comment] 2015-11-05 18:33
Ah OK, that makes sense :)

On 5 November 2015 13:10:08 GMT+00:00, Ryan Abernathey <notifications@github.com> wrote:
>The only way to get all three different FFTW datatypes required for
>pyfftw is to do
>```bash
>$ ./configure --enable-threads --enable-shared
>$ make
>$ sudo make install
>$ ./configure --enable-threads --enable-shared --enable-float
>$ make
>$ sudo make install
>$ ./configure --enable-threads --enable-shared --enable-long-double
>$ make
>$ sudo make install
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hgomersall/pyFFTW/issues/70#issuecomment-154055809

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ghisvail** [comment] 2016-01-30 16:18
Same on Debian. Some architectures do not have FFTW compiled with long-double.

One solution could be to use `pkgconfig` to detect whether each precision is available.

**Comment by hgomersall** [comment] 2016-01-30 21:00
I'm keen for help on this. Some thought it needed as to how to implement and test this properly, so I'd welcome any input.

**Comment by ghisvail** [comment] 2016-02-10 13:48
This is the patch I currently apply on Debian to build on architectures which do not have all versions of FFTW:
```
From: Ghislain Antony Vaillant <ghisvail@gmail.com>
Date: Mon, 1 Feb 2016 23:08:52 +0000
Subject: Detect fftw libraries using pkgconfig.

---
 setup.py | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/setup.py b/setup.py
index 562540c..065289b 100644
--- a/setup.py
+++ b/setup.py
@@ -93,8 +93,9 @@ def get_libraries():
         libraries = ['libfftw3-3', 'libfftw3f-3', 'libfftw3l-3']
 
     else:
-        libraries = ['fftw3', 'fftw3f', 'fftw3l', 'fftw3_threads', 
-                     'fftw3f_threads', 'fftw3l_threads']
+        import pkgconfig
+        libraries = [lib for lib in ("fftw3", "fftw3f", "fftw3l") \
+                     if pkgconfig.exists(lib)]
 
     return libraries
```

**Comment by hgomersall** [comment] 2016-02-10 14:10
Is that sufficient? How is the lack of imported symbols supported?

**Comment by ghisvail** [comment] 2016-02-10 15:27
Well most [builders](https://buildd.debian.org/status/package.php?p=pyfftw) reported successful compilation. The test suite is not run though, as I assumed that it would fail for missing precisions.

**Comment by rabernat** [comment] 2016-02-10 15:33
Perhaps if the other precisions are not available, the inputs can be typecast (with a warning). That would be the most desirable behavior from an end user's perspective.

**Comment by hgomersall** [comment] 2016-02-11 12:37
@rabernat certainly, that would be sensible. I suspect the "right" way to do this is to have a capabilities look up, but with it working relatively seamlessly for the interfaces and builders, and raising errors when the FFTW class is used directly (as it currently does).

**Comment by hgomersall** [comment] 2016-04-22 12:08
Is it reasonable to require fftw and fftwf? Is the problem only with fftwl?

**Comment by UncleGoogle** [comment] 2016-09-12 14:44
The same problem on openSuse Leap 42.1 x86_64

Maybe it is dummy question but where is `configure` file?*  There is only conf.py in the main branch...
*to do things like this:  `./configure --enable-threads --enable-shared`

**Comment by hgomersall** [comment] 2016-09-12 14:58
@UncleGoogle because we don't use autotools.

**Comment by UncleGoogle** [comment] 2016-09-12 19:57
@hgomersall ok. I've just read more documentation, but still don't know you to do things listed by @rabernat. My builds failed in both openSuse and RaspberryPi with exatcly the same error code. Could you please describe how to compile git source with `--enable-threads --enable-shared` options?

**Comment by hgomersall** [comment] 2016-09-13 07:32
@UncleGoogle ah, I understand. @rabernat is talking about compiling FFTW (the underlying library the pyfftw binds). It's plausible though that Suse has different packages for each version of FFTW which you can install from the package manager. Certainly debian systems do.

**Comment by UncleGoogle** [comment] 2016-09-14 12:52
Yes, I didin't noticed that it was about FFTW itself. Now it works. Thanks for help!

**Comment by itdaniher** [comment] 2017-01-22 21:17
It'd be great if this was called out in the docs. I didn't notice this issue until after I spent an hour or two debugging my fftw install. Compiling and installing the same library three times only makes sense in the context of compile-time numerical optimization, which is well beyond what I expected to have to deal with when debugging a "pip install" fail. 

An alternative to calling this out in the docs might be pulling libfftw at install time (from http://www.fftw.org/fftw-3.3.6-pl1.tar.gz) and compiling the appropriate / required versions? Downsides, having to keep track of what flags go with what platforms, upside is that a "pip install PyFFTW" would work regardless of whatever distro has packaged whichever versions of libfftw.

Either way, thanks to everyone for the useful bindings and associated collateral!

**Comment by fredRos** [comment] 2017-04-27 11:11
I implemented this functionality a long time ago in my mpi branch #67 It was quite a hack I have to admit but python setuptools didn't aid much in this regard. I agreed with @hgomersall to split my pr into several, and the first one should resolve this issue by compiling binding only for the installed FFTW libraries; i.e., it will not compile FFTW for the user but use whatever is there.

**Comment by hgomersall** [comment] 2017-04-27 11:19
Yeah, this is definitely should be something that is handled better, and I'm keen to see PRs to that end should you feel keen (even if it's just a doc update in the short term).

Not so keen on statically compiling libs into the python installation. I think this should be up to the package manager. We do it on Windows because that's Windows. Beyond that, I've no clear idea about the best way to do it.

A big issue is making sure the correct scheme lookups are created inside the main `.pyx` file.

**Comment by lzkelley** [comment] 2017-10-09 16:29
I *think* this is the reason I'm unable to install pyfftw on a cluster account.  Is there a workaround that doesn't require root access?

```
gcc -pthread -shared -L/n/home00/lkelley/.conda/envs/py35/lib -Wl,-rpath=/n/home00/lkelley/.conda/envs/py35/lib,--no-as-needed build/temp.linux-x86_64-3.6/scratch/tmp/pip-build-vfnn_g1g/pyfftw/pyfftw/pyfftw.o -L/n/home00/lkelley/.conda/envs/py35/lib -lfftw3 -lfftw3f -lfftw3l -lfftw3_threads -lfftw3f_threads -lfftw3l_threads -lpython3.6m -o build/lib.linux-x86_64-3.6/pyfftw/pyfftw.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lfftw3f
    collect2: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/n/home00/lkelley/.conda/envs/py35/bin/python -u -c "import setuptools, tokenize;__file__='/scratch/tmp/pip-build-vfnn_g1g/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qvv4x3tg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /scratch/tmp/pip-build-vfnn_g1g/pyfftw/
```

**Comment by fredRos** [comment] 2017-10-09 19:43
Did you try to install pyfftw from conda forge? That would pull in the conda fftw package that comes with the `libfftw3f.so`. Obviously that fftw lib wasn't built and fine tuned to your cluster but it would at least allow you to install pyfftw.

    conda config --add channels conda-forge
    conda install pyfftw

**Comment by jakirkham** [comment] 2018-03-16 06:04
Appears to be a duplicate of issue ( https://github.com/pyFFTW/pyFFTW/issues/27 ), which I believe was solved in PR ( https://github.com/pyFFTW/pyFFTW/pull/189 ). Going to close as it is a duplicate at least. Though would encourage people to follow the aforementioned issue for confirmation that it was fixed.

**Closed by jakirkham** 2018-03-16 06:04 UTC
Labels: enhancement, help wanted, pull request welcome
