### ISSUE TITLE
pocketfft and numpy/scipy monkeypatching

### ISSUE THREAD

**Issue by rgommers** [pyFFTW/pyFFTW#243] opened 2018-09-24 12:53 UTC
Hi, feel free to close this straight away - I just wanted to point out https://github.com/numpy/numpy/pull/11888, which is getting closer to ready for merging. It replaces `fftpack` with `pocketfft` in `numpy`, and if that looks good the same may be done for `scipy`. Hopefully that's completely irrelevant to how pyFFTW interacts with `numpy` and `scipy` (I suspect so), but I wanted to ping you just in case - best not to find out after the fact.

**Comment by hgomersall** [comment] 2018-09-24 13:10
That's great thanks. I'll leave this open as a place holder for any potential gotchas.

**Comment by grlee77** [comment] 2018-09-24 17:50
Thanks! Without reviewing that PR in detail, do you know if the `pocketfft` backend still always uses double precision or does it behave more like scipy's fftpack (and pyFFTW's numpy interfaces) where float32 or complex64 input -> complex64 output? There was some code in the test suite to work around these differences in dtype handling that may need to be upated if the behavior is different than before.

Another issue is that in #242, we recently started importing directly from `numpy.fft.fftpack` in some tests rather than from `numpy.fft` to avoid test failures due to `mkl_fft` monkeypatching that was present in some of Anaconda's NumPy builds (there is a lack of OpenBLAS-based numpy+scipy packages available on Windows). I suppose we can use a similar workaround with `pocketfft`.

**Comment by mreineck** [comment] 2018-09-24 19:51
`pocketfft` only supports double precision at the moment. Single precision would be easy to add, but I'm not sure there's any need.

The main goals of proposing the library for `numpy` were:
 - better accuracy for real-valued FFTs with large prime factors
 - better performance (by using Bluestein's algorithm) for any FFT with large prime factors.

**Comment by grlee77** [comment] 2018-09-24 21:59
> pocketfft only supports double precision at the moment. Single precision would be easy to add, but I'm not sure there's any need.

Sounds good. Because it is still double precision only then the test suite will hopefully work as is aside from fixing the attempted import from `numpy.fft.fftpack`.  If I recall correctly the `mkl_fft` monkeypatching was causing failures in the test suite because it would use single precision while the assumptions made in the tests were that NumPy always used double precision.

**Comment by jakirkham** [comment] 2018-10-21 21:38
> Single precision would be easy to add, but I'm not sure there's any need.

@mreineck, this is valuable when doing image registration or applying some filters in Fourier space on large data. Eschewing the extra precision can be a nice performance bump and is often good enough in these cases.

**Comment by mreineck** [comment] 2019-02-25 09:10
Independent of the sp/dp question, I get pyfftw errors when running it in conjunction with the experimental numpy 1.17.

```
/usr/lib/python3/dist-packages/pyfftw/interfaces/numpy_fft.py:187: in ifftn
    calling_func, **_norm_args(norm))
/usr/lib/python3/dist-packages/pyfftw/interfaces/_utils.py:128: in _Xfftn
    FFTW_object = getattr(builders, calling_func)(*planner_args)
/usr/lib/python3/dist-packages/pyfftw/builders/builders.py:404: in ifftn
    avoid_copy, inverse, real, **_norm_args(norm))
/usr/lib/python3/dist-packages/pyfftw/builders/_utils.py:261: in _Xfftn
    flags, threads, normalise_idft=normalise_idft, ortho=ortho)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.

pyfftw/pyfftw.pyx:1280: RuntimeError

```
This is in code that runs flawlessly  with numpy 1.16.
I can try to provide a small testcase if that helps.

**Comment by mreineck** [comment] 2019-02-25 09:27
> @mreineck, this is valuable when doing image registration or applying some filters in Fourier space on large data. Eschewing the extra precision can be a nice performance bump and is often good enough in these cases.

I do not see any significant potential for speedup here. Pocketfft does not use vector instructions, so we do not benefit from longer register vectors, and standard single precision calculations are not faster than double precision these days. (The trigonometric calls for the twiddle factors may be an exception, but they use only an insignificant fraction of the whole FFT.)

There is a certain range of FFT lengths where the single precision data would still fit into a cache, while the double precision data is already too large, but again this only affects a small subset of FFT lengths.

In the case of 1D FFTs with around a billion entries, the space overhead of storing data and twiddle factors in double precision can become significant, I agree. But again, the `fftpack` implementation currenty in scipy will break silently for many lengths larger than about 10 million. So I expect this is not really heavily used at the moment.

**Comment by grlee77** [comment] 2019-02-25 13:49
> I can try to provide a small testcase if that helps.

That would be helpful. Do any of the test cases fail? I created a new environment with current numpy and pyFFTW each built from master and the tests seem to pass for me. 

I built the test environment using the following sequence of steps:
```
# create a new Python 3.7 environment with scipy, cython, fftw and pytest
conda create -n np117 -c conda-forge python=3.7 cython scipy fftw pytest
conda activate np117

# remove numpy 1.16.1 installed by conda
conda uninstall numpy --force

# build numpy from source
git clone git@github.com:numpy/numpy.git
cd numpy
python setup.py build_ext --inplace -j 4
pip install -e . -v
cd ..

# build pyFFTW from source
git clone git@github.com:pyFFTW/pyFFTW.git
cd pyFFTW
pip install -e . -v

# run numpy interface tests
py.test test/test_pyfftw_numpy_interface.py -v
```

**Comment by mreineck** [comment] 2019-02-25 15:59
When running the following code:
```
import numpy as np
import pyfftw

print("Numpy version: ", np.version.full_version)

arr=np.zeros((32,4,4),dtype=np.complex128)
a2=pyfftw.interfaces.numpy_fft.fftn(arr,axes=(0,))
a3=pyfftw.interfaces.numpy_fft.ifftn(a2,axes=(0,))
```

I get

```
Numpy version:  1.17.0.dev0+67e20d0
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    a2=pyfftw.interfaces.numpy_fft.fftn(arr,axes=(0,))
  File "/usr/lib/python3/dist-packages/pyfftw/interfaces/numpy_fft.py", line 169, in fftn
    calling_func, **_norm_args(norm))
  File "/usr/lib/python3/dist-packages/pyfftw/interfaces/_utils.py", line 128, in _Xfftn
    FFTW_object = getattr(builders, calling_func)(*planner_args)
  File "/usr/lib/python3/dist-packages/pyfftw/builders/builders.py", line 382, in fftn
    avoid_copy, inverse, real, **_norm_args(norm))
  File "/usr/lib/python3/dist-packages/pyfftw/builders/_utils.py", line 261, in _Xfftn
    flags, threads, normalise_idft=normalise_idft, ortho=ortho)
  File "pyfftw/pyfftw.pyx", line 1280, in pyfftw.pyfftw.FFTW.__cinit__
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.
```

**Comment by mreineck** [comment] 2019-02-26 09:35
I just tried again with a conda installation - same result.

**Comment by mreineck** [comment] 2019-05-02 11:26
Any news on this? Please let me know if I can provide more data.
(Just verified that the problem still occurs with an up-to-date numpy checkout.)

**Comment by grlee77** [comment] 2019-05-02 17:54
@mreineck:
I could not reproduce the error on an OS X machine. The example you provided ran fine. I am traveling and do not have access to a linux machine for the next 10 days or so.

Also, how are you installing Numpy 1.17? http://wheels.scipy.org did not seem to have an OS X wheel so I just modified conda-forge's numpy recipe slightly so it would build from Numpy's master branch and used that.

**Comment by mreineck** [comment] 2019-05-03 07:30
> I am traveling and do not have access to a linux machine for the next 10 days or so.

No problem at all!
My only (slight) worry is that there is some otherwise undetected breakage in pocketfft, and that it may be quite inconvenient to fix this after the numpy 1.17 release. But it seems we still have some time until then.

> Also, how are you installing Numpy 1.17?

Just by running `python3 setup.py install --user` on a cloned repository. So far this has worked nicely, but please let me know if additional steps are needed.

**Comment by grlee77** [comment] 2019-05-15 19:03
Hi @mreineck, so far I am also unable to reproduce your issue on an Ubuntu 16.04 machine with:

```
python                    3.7.3                h5b0a415_0    conda-forge
cython                    0.29.7           py37he1b5a44_0    conda-forge
fftw                      3.3.8           nompi_h7f3a6c3_1105    conda-forge
pytest                    4.5.0                    py37_0    conda-forge
```
and the following built from source and installed via pip:
```
numpy                     1.17.0.dev0+75ea05f           dev_0    <develop>
pyfftw                    0.11.1+5.ge9966e5           dev_0    <develop>
```

The pyFFTW example you provided and the numpy interface tests all pass.

**Comment by mreineck** [comment] 2019-05-15 19:53
Thanks for checking!
I have no idea what's happening here ... let's just wait for numpy 1.17 and see whether other people report this as well. If so, that hopefully gives us enough data to understand the source of the problem.

**Comment by mreineck** [comment] 2019-08-01 11:24
OK, I tried to reproduce this with the official numpy 1.17 package, and things seem to work now. Sorry for the noise ... I have no idea what went wrong on my end.

**Comment by grlee77** [comment] 2019-08-01 14:13
Thanks for the update. I will go ahead and close this then.

**Closed by grlee77** 2019-08-01 14:13 UTC
