### ISSUE TITLE
RuntimeWarning: overflow encountered in long_scalars

### ISSUE THREAD

**Issue by david-hoffman** [pyFFTW/pyFFTW#136] opened 2016-10-01 18:40 UTC
I've been getting the following error when attempting to perform an fft on a large array:

``` console
C:\Anaconda3\lib\site-packages\pyfftw\builders\_utils.py:127: RuntimeWarning: overflow encountered in long_scalars
  output_array = pyfftw.empty_aligned(output_shape, output_dtype)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-65-12bb74fa6d42> in <module>()
----> 1 pyfftw.fftn(a);

C:\Anaconda3\lib\site-packages\pyfftw\interfaces\numpy_fft.py in fftn(a, s, axes, norm, overwrite_input, planner_effort, threads, auto_align_input, auto_contiguous)
    181     return _Xfftn(a, s, axes, overwrite_input, planner_effort,
    182             threads, auto_align_input, auto_contiguous,
--> 183             calling_func, normalise_idft=normalise_idft, ortho=ortho)
    184
    185 def ifftn(a, s=None, axes=None, norm=None, overwrite_input=False,

C:\Anaconda3\lib\site-packages\pyfftw\interfaces\_utils.py in _Xfftn(a, s, axes, overwrite_input, planner_effort, threads, auto_align_input, auto_contiguous, calling_func, normalise_idft, ortho)
    123         planner_args = (a, s, axes) + args
    124
--> 125         FFTW_object = getattr(builders, calling_func)(*planner_args)
    126
    127         # Only copy if the input array is what was actually used

C:\Anaconda3\lib\site-packages\pyfftw\builders\builders.py in fftn(a, s, axes, overwrite_input, planner_effort, threads, auto_align_input, auto_contiguous, avoid_copy)
    362     return _Xfftn(a, s, axes, overwrite_input, planner_effort,
    363             threads, auto_align_input, auto_contiguous,
--> 364             avoid_copy, inverse, real)
    365
    366 def ifftn(a, s=None, axes=None, overwrite_input=False,

C:\Anaconda3\lib\site-packages\pyfftw\builders\_utils.py in _Xfftn(a, s, axes, overwrite_input, planner_effort, threads, auto_align_input, auto_contiguous, avoid_copy, inverse, real)
    125         a_copy = a.copy()
    126
--> 127     output_array = pyfftw.empty_aligned(output_shape, output_dtype)
    128
    129     flags = [planner_effort]

pyfftw\utils.pxi in pyfftw.pyfftw.empty_aligned (C:\projects\pyfftw\pyfftw\pyfftw.c:3958)()

pyfftw\utils.pxi in pyfftw.pyfftw.empty_aligned (C:\projects\pyfftw\pyfftw\pyfftw.c:3705)()

ValueError: negative dimensions are not allowed
```

I'm not familiar with the code base but it seems like `output_shape` is overflowing.

A small code snippet that can reproduce the error on my system is:

``` python
import numpy as np
import pyfftw.interfaces.numpy_fft as pyfftw
a = np.zeros((512, 512, 512))
pyfftw.fftn(a)
```

**Comment by hgomersall** [comment] 2016-10-01 19:43
I can't reproduce this (partly because I'm crashing due to low memory, though it seems to get to the actual run stage which yours doesn't appear to be doing). If you just construct an empty array with `a = pyfftw.empty_aligned((512, 512, 512))` what happens? (you'll need to import the whole namespace of pyfftw - `import pyfftw`).

Windows has some annoying bugs in which what should be 64-bit ints are actually 32-bit ints. This smells like it might be similar - but then your dimensions should fit into a 32-bit int.... hmmm.

What is the smallest array you can trigger this problem with?

**Comment by hgomersall** [comment] 2016-10-01 19:44
Just to be clear, are you running the latest version?

**Comment by david-hoffman** [comment] 2016-10-01 21:54
The version I'm running is 0.10.4 and I'm running it on 64-bit Windows 10.

I actually tried `a = pyfftw.empty_aligned((512, 512, 512)` (I should have mentioned this) and no exception is raised.

I put some print statements into pyfftw/builders/_utils.py to try and track down the problem. I printed out `output_shape` and `output_dtype` directly before `output_array = pyfftw.empty_aligned(output_shape, output_dtype)` (line 127):
```python
output_shape = (512, 512, 512)
output_dtype = dtype('complex128')
```
as expected.

What's strange is that I tried adding another print statement:
```python
print(pyfftw.empty_aligned(output_shape))
```
which should trigger an exception but doesn't. You can specify the `output_dtype` as well and still no error. But if you put in the following print statement (this was a sanity check for me):
```python
print(pyfftw.empty_aligned(output_shape, output_dtype))
```
the print statement triggers the `ValueError` as would be expected. Perhaps something's funky with the `output_dtype` even though when printed it seems reasonable?

I'm checking the exact size at which the exception is raised but for now I can say that `a = np.zeros((511, 512, 512))` works but `a = np.zeros((512, 512, 512))` fails.

**Comment by david-hoffman** [comment] 2016-10-03 12:15
From what I've found, on my computer `a = np.zeros(134217726)` fails and `a = np.zeros(134217725)` succeeds.

**Comment by hgomersall** [comment] 2016-10-03 13:11
Is this numpy failing then? Intriguing. I have encountered issues with int64 being actually int32 but this is a weird size (2**27 - 2).

**Comment by david-hoffman** [comment] 2016-10-04 13:07
I just tested on scientific linux and its not a problem. Seems to be a windows specific issue.

**Comment by hgomersall** [comment] 2016-10-04 13:21
right, but is it numpy or pyfftw?

**Comment by david-hoffman** [comment] 2016-10-04 23:15
I did a little more digging and the components of the `output_shape` tuple are of type `np.int32`. This is probably where the problem comes in as its a signed integer and should only be able to go between `-2**16` and `2**16 - 1`. Explicitly casting the members of `output_shape` to Python's builtin `int` type fixes the problem, though I doubt the best way to solve the problem.

You were right to suspect something wrong with numpy, on my windows machines I get:
```python
In [1]: import numpy as np

In [2]: np.iinfo(np.int32)
Out[2]: iinfo(min=-2147483648, max=2147483647, dtype=int32)
```

So what `numpy` identifies as `int32` is really `int64` which is why explicitly casting in the python code sidesteps the problem.

My guess is it gets mistakenly cast to `int32` (because that's what `numpy` identifies it as) somewhere in the `empty_aligned` function. I couldn't find the `empty_aligned` function in the repo (sorry for my idiocy) so I couldn't really go deeper.

But I can at least hot fix the code now while waiting for a more appropriate patch.

**Comment by hgomersall** [comment] 2016-10-05 08:20
I still don't understand precisely where the problem is occurring. Is it on a call to `numpy.zeros`, or is in something in `pyfftw` that you can't access?

**Comment by david-hoffman** [comment] 2016-10-05 11:26
Sorry I left that part out.

I'm pretty sure that the issue is in `pyfftw.empty_align` but I can't find that function in the repo. Is it part of FFTW?

**Comment by hgomersall** [comment] 2017-03-14 16:44
Apologies for the delay! Yes, it is in [utils.pxi](https://github.com/pyFFTW/pyFFTW/blob/master/pyfftw/utils.pxi).

**Comment by hyliu1989** [comment] 2017-09-15 07:31
I think this problem can only happen in Windows machine since the default int type in Windows is 32-bit instead of 64-bit. The solution would be forcing the type to be int64 in Cython codes whenever there is a size counting.

**Comment by hyliu1989** [comment] 2017-09-15 21:34
A quick workaround is to add `cdef long long array_length` at the beginning of body of cpdef empty_aligned() in pyfftw/utils.pxi
This way we force that variable to be 64-bit integer.

**Comment by GeoffBarrett** [comment] 2017-12-21 20:15
This is still an issue for Windows. Tried pyFFTW-0.10.5 a well.

**Comment by hgomersall** [comment] 2017-12-22 12:21
Yeah, I see what's happening here. Can someone write a test that exercises this?

**Comment by jakirkham** [comment] 2018-03-16 06:32
Solved by PR ( https://github.com/pyFFTW/pyFFTW/pull/192 ), correct? Should we close?

**Comment by jakirkham** [comment] 2018-03-16 06:34
@GeoffBarrett, we haven't made a 0.10.5 release. Could you please run the following in a Python interpreter and report what you see?

```python
import pyfftw
pyfftw.__version__
```

**Comment by GeoffBarrett** [comment] 2018-03-16 14:22
@jakirkham I recompiled after #192 (shortly after I made my comment) and I haven't had the issue since. The 0.10.5 I was referring to was that which I got from [bintray 0.10.5 files](https://bintray.com/hgomersall/generic/PyFFTW-development-builds/0.10.5#files).

**Comment by hgomersall** [comment] 2018-09-14 16:53
I think this is fixed. Closing. Please reopen if it is still an issue.

**Closed by hgomersall** 2018-09-14 16:53 UTC
