### ISSUE TITLE
RuntimeError for N-D arrays on anaconda distribution with mkl optimizations

### ISSUE THREAD

**Issue by jonaballe** [pyFFTW/pyFFTW#40] opened 2014-04-21 19:34 UTC
Hello.

I have started to rely heavily on the anaconda python distribution because of its simple maintenance and because of their MKL optimized linear algebra code in numpy/scipy (which is free for academic use). In terms of FFT implementations, however, they provide nothing compared to FFTW, which is why I use pyFFTW for that (and I want to say a big thank you for providing this well-designed set of wrappers!).

Unfortunately, I just ran into the following error (in pyfftw.pyfftw.FFTW.**cinit** (pyFFTW/pyfftw/pyfftw.c:7613):

"RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug."

It is reproducible with the following three lines of code:

from numpy import empty
from pyfftw.interfaces.numpy_fft import rfft2
rfft2( empty( ( 2, 2, 50, 50 ) ) )

The exception is thrown only when I'm using the MKL optimization package. Everything is fine with arrays of up to three dimensions.

I am somewhat puzzled as to why this happens, and not sure whether it is a bug in the anaconda distribution or in pyfftw (or fftw). But having fast linear algebra and fast fft at the same time is critical for my work. As I am unaware of the internal structure of pyfftw, can you assist me in figuring out this problem?

Thanks,
Johannes

**Comment by hgomersall** [comment] 2016-01-30 21:41
It's hard to see what we can do from the pyfftw end for this. If the MKL is exporting symbols that another library uses (specifically to be API compatible), then it's sort of the MKL's job to not cause problems. I'm inclined to mark this `wontfix` and document the workaround.

**Comment by hgomersall** [comment] 2016-01-30 21:42
Actually, is this still a problem? I think it's probably a job for anaconda if it is.

**Comment by jonycgn** [comment] 2016-02-01 23:03
so far, i've been using the -Bsymbolic workaround successfully. documenting the problem with the workaround seems appropriate ... so as for me, you can go ahead and close the issue.

**Comment by hgomersall** [comment] 2016-02-02 10:33
@drwells You seem to suggest that Anaconda just works when the import is in the right order. Is this correct? When is the -Bsymbolic workaround necessary?

**Comment by drwells** [comment] 2016-02-02 18:05
That was nearly two years ago; I don't remember. I'll try and reproduce this in the next week.

**Comment by jonycgn** [comment] 2016-02-06 18:57
the workaround should be necessary in general, since you don't really know what other modules that you are importing depend on, and in what order they import stuff.

**Comment by aganders3** [comment] 2016-04-13 23:25
We're not using pyFFTW, but ran into the same problem with our in-house FFTW wrappers. I was able to reproduce the problem on OS X and Linux. Changing the import order *does* fix it, but that's not a solution we can depend on. I think this issue will be more common now, since Continuum has made MKL free (and default) in new versions of Anaconda.

There is a [conversation in Anaconda Support](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/zXT3dRsKK10) about this now (which links here).

**Comment by hgomersall** [comment] 2016-04-14 09:38
Thanks Ashley, it does sound like an issue that needs sorting from Anaconda's end (or perhaps Intel).

Out of interest, is there a reason why your doing your own in house wrappers rather than using pyfftw? Does it lack something you need?

**Comment by aganders3** [comment] 2016-04-14 17:02
As far as I know there is nothing specific pyfftw is lacking - I think it's just due to the way this project evolved. We are an academic-ish site working on MRI so we had some FFTW wrappers in C that simplify some of our most common operations. Later we re-wrapped these for convenience when we started using Python. We also use an in-house C/C++ arrays that can wrap Numpy arrays, in part because it provides a similar interface to our industry partners' code. At some point we will probably give pyfftw a chance in comparison, but this isn't really the focus of our research so we have to save it for rainy days.

**Comment by hgomersall** [comment] 2016-04-14 17:22
Ah ok. I was interested insomuch as I wondered if there was something seriously lacking or that wasn't being addressed (and to perhaps persuade you to help with the missing bits :) ).

**Comment by grlee77** [comment] 2016-06-12 00:11
For anaconda users not on Windows, please try the `pyfftw` package available from conda-forge:
`conda install -c conda-forge pyfftw`

It has been built with static linking and using the -Bsymbolic linker flag (solution thanks to @jonycgn )

If you still see encounter this problem, please raise an issue [over there](https://github.com/conda-forge/pyfftw-feedstock`)

**Closed as completed** 2018-03-16 06:14 UTC
