### ISSUE TITLE
Poor performance of conda-forge package

### ISSUE THREAD

**Issue by sambarluc** [pyFFTW/pyFFTW#184] opened 2017-08-17 10:58 UTC
From https://github.com/pyFFTW/pyFFTW/issues/106#issuecomment-322802960

Ingredients:

- OS Linux 4.4.0-92, Ubuntu):

- conda base packages (miniconda):
>     numpy 1.13.1 py36_0
>     python 3.6.2 0
>     mkl 2017.0.3 0

- pyFFTW compiled via pip:
>     pyFFTW (0.10.4)

- pyFFTW installed from conda-forge:
>     pyfftw 0.10.4 np113py36_1 conda-forge

## **The problem**: numpy is faster than conda-forge pyFFTW!

    Numpy (with mkl)
```
In [1]: import numpy as np
In [2]: x=np.random.random(4096)
In [3]: %timeit np.fft.fft(x)
79.1 µs ± 661 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

    Locally compiled pyFFTW from pip, works great:
```
In [6]: import pyfftw
In [7]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [8]: a[:] = x
In [9]: fftobj = pyfftw.builders.fft(a)
In [10]: %timeit fftobj()
15.4 µs ± 443 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

BTW, it speeds up substantially also with interfaces, and I didn't even switch on the cache.

    conda-forge pyFFTW
```
In [1]: import numpy as np
In [2]: import pyfftw
In [3]: x=np.random.random(4096)
In [4]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [5]: a[:] = x
In [6]: fftobj = pyfftw.builders.fft(a)
In [7]: %timeit fftobj()
110 µs ± 202 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [8]: %timeit np.fft.fft(x)
77.9 µs ± 73.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

   conda-forge pyFFTW, reordering imports:
```
In [1]: import pyfftw
In [2]: import numpy as np
In [3]: x=np.random.random(4096)
In [4]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [5]: a[:] = x
In [6]: fftobj = pyfftw.builders.fft(a)
In [7]: %timeit fftobj()
111 µs ± 427 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

   conda-forge pyFFTW, MKL-unsupported transform:
```
In [1]: import pyfftw
In [2]: import numpy as np
In [3]: shape = (1, 1, 4096)
In [4]: x=np.random.random(np.prod(shape)).reshape(shape)
In [5]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [6]: a[:] = x
In [7]: fftobj = pyfftw.builders.fft(a)
In [9]: %timeit fftobj()
116 µs ± 5.72 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [10]: %timeit np.fft.fft(x)
78 µs ± 730 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

   same on a larger array:
```
In [9]: shape = (100, 1, 4096)
In [10]: x=np.random.random(np.prod(shape)).reshape(shape)
In [11]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [12]: a[:] = x
In [13]: %timeit np.fft.fft(x)
7.87 ms ± 9.75 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In [14]: fftobj = pyfftw.builders.fft(a)
In [15]: %timeit fftobj()
11.3 ms ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

So, at the moment, I am actually using pyFFTW from pip (locally compiled), and use it for 1D transforms (or 2D over 2 axes, etc), whereas I use numpy.fft for other transforms.

**Comment by grlee77** [comment] 2017-08-17 13:44
The pyFFTW package is built using FFTW libraries compiled with the following flags:
https://github.com/conda-forge/fftw-feedstock/blob/master/recipe/build.sh

I am not sure how that may differ from the local FFTW libs being used when you install via pip.  

It is odd that numpy is faster despite being single-threaded.  I will try testing with these sizes later today and see if I can reproduce or figure out where the issue is.

The numpy FFT routines are efficient for power of two size transforms such as 4096, although for a transform of size (100, 1, 4096) I would have expected the multiple threads enabled by pyFFTW to make it substantially faster.  If you were to use transform sizes that are not a multiple of powers of 2, 3 and 5 you should see a much bigger relative advantage for pyFFTW vs numpy.  100 = 5*5*2*2 so it is still a favorable size for numpy as well.

**Comment by hgomersall** [comment] 2017-08-17 15:12
@grlee77 Has the default thread situation changed, or is it still 1 unless otherwise specified?

**Comment by sambarluc** [comment] 2017-08-17 15:39
Hi, here comes the test:

```
In [1]: import pyfftw
In [2]: import numpy as np
In [3]: shape = (29, 1, 13*7*11*17)
In [4]: shape
Out[4]: (29, 1, 17017)
In [5]: x=np.random.random(np.prod(shape)).reshape(shape)
In [6]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [7]: a[:] = x
In [8]: %timeit np.fft.fft(x)
33.5 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
In [9]: fftobj = pyfftw.builders.fft(a)
In [10]: %timeit fftobj()
35.6 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Gap reduced, but `numpy` still wins...

Concerning which version of libfftw, I use the ubuntu package:

```
$ apt-cache show libfftw3-dev
Package: libfftw3-dev
Priority: optional
Section: libdevel
Installed-Size: 15792
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Science Team <debian-science-maintainers@lists.alioth.debian.org>
Architecture: amd64
Source: fftw3
Version: 3.3.4-2ubuntu1
Replaces: fftw3-dev
Provides: fftw3-dev
Depends: libfftw3-bin (= 3.3.4-2ubuntu1), libfftw3-double3 (= 3.3.4-2ubuntu1), libfftw3-long3 (= 3.3.4-2ubuntu1), libfftw3-quad3 (= 3.3.4-2ubuntu1), libfftw3-single3 (= 3.3.4-2ubuntu1)
Suggests: libfftw3-doc
Conflicts: fftw3-dev
Filename: pool/main/f/fftw3/libfftw3-dev_3.3.4-2ubuntu1_amd64.deb
Size: 2104150
MD5sum: 198c872a125bc649942074e0645c3106
SHA1: b89f719c2da4d0d3d588b2664f98dddd1b1c2f8c
SHA256: 0e74ef53e060d6ba58d219f376b2324594c3e70b35710fe9a502f4d1eb17710f
Description-en_GB: Library for computing Fast Fourier Transforms - development
 The FFTW library computes Fast Fourier Transforms (FFT) in one or more
 dimensions. It is extremely fast. This package contains the statically
 linked library, header files and test programs.
 .
 This package contains the header files and static libraries. For
 documentation, see libfftw3-doc.
Description-md5: 0458906aced3a568dab153e7bdeb04f0
Multi-Arch: same
Homepage: http://fftw.org
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
```

**Comment by grlee77** [comment] 2017-08-17 16:02
@hgomersall:   No, it hasn't changed.  I had forgotten the default was one because I usually end up using my own `functools.partial` wrapper where I have set a different default.

I also am seeing slower performance in pyFFTW with a single thread for the examples given above, but I am not seeing a difference whether I use the conda-forge package or a pip install of 0.10.4.

The following are using numpy1.13.1 from conda-forge and pyFFTW built from current master using the FFTW libraries from conda-forge.  With two or more threads pyFFTW is faster (Tested on a workstation with two 8-core CPUs running Ubuntu 14.04)

```python
    import numpy as np
    import pyfftw
    shape = (100, 1, 4096)
    x=np.random.standard_normal(shape)
    a = pyfftw.empty_aligned(x.shape, dtype=x.dtype)
    a[:] = x

    %timeit np.fft.fft(x)
    # 11.9 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

    fftobj = pyfftw.builders.fft(a)
    %timeit fftobj()
    # 15.4 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

    fftobj = pyfftw.builders.fft(a, threads=2)
    %timeit fftobj()
    # 9.46 ms ± 792 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

    fftobj = pyfftw.builders.fft(a, threads=4)
    %timeit fftobj()
    # 4.93 ms ± 72.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

    fftobj = pyfftw.builders.fft(a, threads=8)
    %timeit fftobj()
    # 2.81 ms ± 19.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

    fftobj = pyfftw.builders.fft(a, threads=16)
    %timeit fftobj()
    #2.14 ms ± 129 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by grlee77** [comment] 2017-08-17 16:05
>> Gap reduced, but numpy still wins...

Hmmm.  I noticed that too.  Perhaps the numpy FFT has improved in recent years.  Also, I guess the size of the first dimensions should not matter unless `fft` were replaced with `fftn`.  Otherwise only the last axis is being transformed.  Either way, the question remains regarding why single-threaded performance seems better in numpy.

**Comment by grlee77** [comment] 2017-08-17 16:23
Here is an example using a prime number (as demonstrated in the `scipy.fftpack.next_fast_len` examples) where pyFFTW is nearly 100 times faster in a single thread:

```python
shape = (10007)
x=np.random.standard_normal(shape)
a = pyfftw.empty_aligned(x.shape, dtype=x.dtype)
a[:] = x

%timeit b = np.fft.fft(x)
228 ms ± 513 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

fftobj = pyfftw.builders.fft(a)
%timeit fftobj()
2.45 ms ± 6.29 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Although, ideally one would pad out to a more favorable transform size at which point numpy.fft is puling ahead again:
```
 %timeit b = np.fft.fft(x, 10125)
373 µs ± 40.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
 fftobj = pyfftw.builders.fft(a, 10125)

%timeit fftobj(x)
660 µs ± 546 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
```

**Comment by hgomersall** [comment] 2017-08-17 17:39
On my dual core i7 5600 @ 2.6Ghz, my times are _quite_ different:
```python
     %timeit np.fft.fft(x)
    # 100 loops, best of 3: 8.37 ms per loop

    fftobj = pyfftw.builders.fft(a)
    %timeit fftobj()
    # 100 loops, best of 3: 2.41 ms per loop

    fftobj = pyfftw.builders.fft(a, threads=2)
    %timeit fftobj()
    # 1000 loops, best of 3: 1.72 ms per loop

    fftobj = pyfftw.builders.fft(a, threads=4)
    %timeit fftobj()
    # 1000 loops, best of 3: 1.52 ms per loop

    fftobj = pyfftw.builders.fft(a, threads=8)
    %timeit fftobj()
    # 1000 loops, best of 3: 1.67 ms per loop

    fftobj = pyfftw.builders.fft(a, threads=16)
    %timeit fftobj()
    # 1 loops, best of 3: 1.73 ms per loop
```

I don't know why the `timeit` output is different, but it's notably quicker than yours in every case - even when the high thread count becomes a burden rather than a help.

**Comment by hgomersall** [comment] 2017-08-17 17:40
Sorry, the last post was based on your first set:
```python
    import numpy as np
    import pyfftw
    shape = (100, 1, 4096)
    x=np.random.standard_normal(shape)
    a = pyfftw.empty_aligned(x.shape, dtype=x.dtype)
    a[:] = x
```

**Comment by grlee77** [comment] 2017-08-17 18:48
@hgomersall 
For reference, the workstation I used in the benchmark above is a bit older and has two of the following CPUs:
```model name	: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz```
It is nominally the same base frequency as your i7, but is on an older 32 nm process as opposed to the 14 nm one on your i7.  I don't think it is too surprising that it might be slower.

On an OS X quad-core laptop (i7-4770HQ @ 2.2 GHz,   22 nm),  I get a comparable numpy time to your system, but pyfftw is still slower than it is for you  (these are with the conda-forge package):
```
numpy:  8.37 ms
pfftw 1-thread:  12.6 ms
pfftw 2-thread:  5.98 ms
pfftw 4-thread:  3.16 ms
pfftw 8-thread:  2.75 ms
pfftw 16-thread:  2.91 ms
```

If I install via pip (using clang compiler and FFTW from homebrew), the result is approximately the same.

**Comment by sambarluc** [comment] 2017-08-18 07:18
@hgomersall `%timit` is difference because we use different versions of python/ipython. I would guess @grlee77 and me are using python 3, while you are using python 2.

**Comment by sambarluc** [comment] 2017-08-18 07:28
I also feel I should stress a point. If you look at my first tests, the point is not that numpy is fast (or slow). I just put numpy as an external reference point. The point is that *`pyFFTW` locally compiled is between 5 and 6 times faster than the conda-forge package*!

**Comment by hgomersall** [comment] 2017-08-18 10:12
Yeah, it looks to me like there is a problem with the conda-forge compiled pyFFTW packages. Should this be pushed upstream? Who's responsible for that?

**Comment by grlee77** [comment] 2017-08-18 17:10
>  The point is that pyFFTW locally compiled is between 5 and 6 times faster than the conda-forge package! Locally compiled pyFFTW beats numpy hands down.

That was not my experience initially, but I have now been able to reproduce the effect.  I had to uninstall the conda-forge FFTW libraries so they wouldn't be found.  Now, a pip install on OS X gives almost 5 times faster performance than with the conda-forge package!

I am one of the maintainers on each of the `conda-forge` feedstocks and can make a PR there if we can identify the source of the problem.  We could open an issue at either:
https://github.com/conda-forge/pyFFTW-feedstock
or
https://github.com/conda-forge/FFTW-feedstock

I will see if I can figure out the source of the performance loss locally by playing with the recipes locally.

**Comment by grlee77** [comment] 2017-08-18 17:19
I think I have ruled out `pyFFTW-feedstock` as the culprit.  I modified the recipe's `meta.yaml` to not have FFTW as a build requirement so that it would not download the FFTW library from conda-forge.  I then modified `build.sh` to use the path to my FFTW install from OS X homebrew (fftw 3.6.2-pl2).  I then run `conda-build` locally and still get good performance.

This means that the difference must be in how the libraries at `FFTW-feedstock` are getting built.  I didn't see anything obviously bad in the [build script](https://github.com/conda-forge/fftw-feedstock/blob/master/recipe/build.sh)

**Comment by grlee77** [comment] 2017-08-18 18:30
Adding the `-O3`to CFLAGS in the FFTW recipe resolves the issue for me locally.  I will open a PR over at the conda-forge feedstock.

**Comment by grlee77** [comment] 2017-08-18 18:50
I repeated the benchmark in **single precision** and with the modified conda-recipe including the -O3 flag.  The benefit of single-threaded pyFFTW over numpy.fft is approximately 10 fold! 

```python
    import numpy as np
    import pyfftw
    import scipy.fftpack
    shape = (100, 1, 4096)
    x=np.random.standard_normal(shape).astype(np.complex64)
    a = pyfftw.empty_aligned(x.shape, dtype=x.dtype)
    a[:] = x

    %timeit np.fft.fft(x)
    # 10.2 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

    %timeit scipy.fftpack.fft(x)
    # 5.95 ms ± 629 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

    fftobj = pyfftw.builders.fft(a)
    %timeit fftobj(x)
    # 1.06 ms ± 1.11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

    fftobj = pyfftw.builders.fft(a, threads=2)
    %timeit fftobj(x)
    # 544 µs ± 1.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

    fftobj = pyfftw.builders.fft(a, threads=4)
    %timeit fftobj(x)
    # 532 µs ± 90.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

    fftobj = pyfftw.builders.fft(a, threads=8)
    %timeit fftobj(x)
    # 377 µs ± 15.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

    fftobj = pyfftw.builders.fft(a, threads=16)
    %timeit fftobj(x)
    # 298 µs ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)    
```

**Comment by sambarluc** [comment] 2017-08-18 19:53
> That was not my experience initially, but I have now been able to reproduce the effect. I had to uninstall the conda-forge FFTW libraries so they wouldn't be found.

Indeed I also removed `conda-forge` before installing the `pip` package and vice-versa. I forgot to mention that. In any case, I'm glad to see that you seem to have identified the cause of the problem!  Thanks for the support.

**Comment by grlee77** [comment] 2017-08-18 20:18
I am closing this as the issue was with the conda-forge FFTW package rather than pyFFTW itself.  A fix is in progress at conda-forge/fftw-feedstock#35 to be followed by a second PR to rebuild pyfftw.

**Closed by grlee77** 2017-08-18 20:18 UTC

**Comment by grlee77** [comment] 2017-08-21 17:02
@sambarluc 
Updated `conda-forge` packages for `pyFFTW` 0.10.4 have been created for OS X and linux.  Please let me know if these do not resolve the performance issue for you.

**Comment by sambarluc** [comment] 2017-08-22 07:15
`conda-forge pyfftw` is almost ten times faster than it used to be, and on par with the locally compiled version. Great! Thanks a lot.

```
In [1]: import pyfftw
In [2]: import numpy as np
In [3]: x=np.random.random(4096)
In [4]: a = pyfftw.empty_aligned(x.shape, dtype='float64')
In [5]: a[:] = x
In [6]: fftobj = pyfftw.builders.fft(a)
In [7]: %timeit fftobj()
14.8 µs ± 359 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [8]: %timeit np.fft.fft(x)
78.7 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

And at least as good for the other benchmarks.
