### ISSUE TITLE
Error installing from PyPI (python 2) on linux mint

### ISSUE THREAD

**Issue by islijepcevic** [pyFFTW/pyFFTW#183] opened 2017-07-11 21:41 UTC
It looks like there is some problem with recognizing FFTW3. I tried also installing following packages, to no avail: `python-fftw`, `libfftw3-3` and `libfftw3-long3`.

On the other hand, installing `python-pyfftw` from debian repositories works, but I get issues similar to [this one](https://github.com/pyFFTW/pyFFTW/issues/112) when using `pyfftw`.

Here is the complete log (same with and without mentioned packages):
```
pip2 install -U pyfftw
Collecting pyfftw
  Downloading pyFFTW-0.10.4.tar.gz (365kB)
    100% |████████████████████████████████| 368kB 1.7MB/s 
Installing collected packages: pyfftw
  Running setup.py install for pyfftw ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VGzDNH/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-AoVVCK-record/install-record.txt --single-version-externally-managed --compile:
    Compiling /tmp/pip-build-VGzDNH/pyfftw/pyfftw/pyfftw.pyx because it depends on /usr/local/lib/python2.7/dist-packages/Cython/Includes/numpy/__init__.pxd.
    [1/1] Cythonizing /tmp/pip-build-VGzDNH/pyfftw/pyfftw/pyfftw.pyx
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pyfftw
    copying pyfftw/version.py -> build/lib.linux-x86_64-2.7/pyfftw
    copying pyfftw/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw
    creating build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    copying pyfftw/builders/builders.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
    creating build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/cache.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    copying pyfftw/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
    running build_ext
    building 'pyfftw.pyfftw' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-VGzDNH
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-VGzDNH/pyfftw
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-VGzDNH/pyfftw/pyfftw
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-VGzDNH/pyfftw/include -I/tmp/pip-build-VGzDNH/pyfftw/pyfftw -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-VGzDNH/pyfftw/pyfftw/pyfftw.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-VGzDNH/pyfftw/pyfftw/pyfftw.o
    In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-VGzDNH/pyfftw/pyfftw/pyfftw.c:462:
    /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    /tmp/pip-build-VGzDNH/pyfftw/pyfftw/pyfftw.c:466:19: fatal error: fftw3.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VGzDNH/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-AoVVCK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-VGzDNH/pyfftw/
```

**Comment by grlee77** [comment] 2017-07-11 22:05
I think you will need the `libfftw3-dev` package to get the FFTW3 libraries and headers.  Once those are in place, the pip install should work.

This same thing came up recently in #181 as well, so perhaps a PR to update/clarify the install documentation is in order. 

I am closing the issue as not a bug, but feel free to continue to comment here if installing the package above does not fix things for you.

**Closed by grlee77** 2017-07-11 22:05 UTC

**Comment by islijepcevic** [comment] 2017-07-13 07:18
Installing `libfftw3-dev` worked like a charm. Thanks!
