### ISSUE TITLE
Building on Python 3.9 / macOS 10.15.6 fails without -Wno-error=implicit-function-declaration

### ISSUE THREAD

**Issue by akx** [pyFFTW/pyFFTW#303] opened 2021-01-31 10:44 UTC
As the title says, building on macOS 10.15.6, Python 3.9 (from Homebrew), fails since there's somehow an implicit `-Werror` in the clang command line that makes clang barf when no headers are used for finding the symbol(s).

```
$ pip list
Package    Version
---------- -------
Cython     0.29.21
numpy      1.20.0
pip        20.3.1
setuptools 51.0.0
wheel      0.36.1
```

```
$ LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include -Wno-error" python setup.py -v build_ext

running build_ext
Link FFTW dynamically
Compiler include_dirs: ['/usr/local/include', '/usr/local/opt/openssl@1.1/include', '/usr/local/opt/sqlite/include', '/Users/akx/envs/pyFFTW/include', '/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/include/python3.9']
3.9.0 (default, Dec  3 2020, 16:09:02)
[Clang 12.0.0 (clang-1200.0.32.27)]
objects: []
libraries: []
include dirs: ['/Users/akx/build/pyFFTW/include', '/Users/akx/build/pyFFTW/pyfftw', '/Users/akx/envs/pyFFTW/lib/python3.9/site-packages/numpy/core/include', '/Users/akx/envs/pyFFTW/include']
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -Wno-error -I/Users/akx/build/pyFFTW/include -I/Users/akx/build/pyFFTW/pyfftw -I/Users/akx/envs/pyFFTW/lib/python3.9/site-packages/numpy/core/include -I/Users/akx/envs/pyFFTW/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/akx/envs/pyFFTW/include -I/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-xs9trp4v/None.c -o /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-xs9trp4v/None.o


clang /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-xs9trp4v/None.o -L/Users/akx/envs/pyFFTW/lib -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -o /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-xs9trp4v/a.out


Checking with includes ['fftw3.h']...ok
objects: []
libraries: ['fftw3']
include dirs: ['/Users/akx/build/pyFFTW/include', '/Users/akx/build/pyFFTW/pyfftw', '/Users/akx/envs/pyFFTW/lib/python3.9/site-packages/numpy/core/include', '/Users/akx/envs/pyFFTW/include']
clang (... as above ...) -c /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-duahkw59/fftw_plan_dft.c -o /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-duahkw59/fftw_plan_dft.o

/var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-duahkw59/fftw_plan_dft.c:2:17: error: implicit declaration of function 'fftw_plan_dft' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                fftw_plan_dft();
                ^
1 error generated.

Checking for fftw_plan_dft...no
objects: []
libraries: ['fftw3f']
include dirs: ['/Users/akx/build/pyFFTW/include', '/Users/akx/build/pyFFTW/pyfftw', '/Users/akx/envs/pyFFTW/lib/python3.9/site-packages/numpy/core/include', '/Users/akx/envs/pyFFTW/include']
clang (... as above ...) -c /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-juiekt3y/fftwf_plan_dft.c -o /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-juiekt3y/fftwf_plan_dft.o

/var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-juiekt3y/fftwf_plan_dft.c:2:17: error: implicit declaration of function 'fftwf_plan_dft' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                fftwf_plan_dft();
                ^
1 error generated.

Checking for fftwf_plan_dft...no
objects: []
libraries: ['fftw3l']
include dirs: ['/Users/akx/build/pyFFTW/include', '/Users/akx/build/pyFFTW/pyfftw', '/Users/akx/envs/pyFFTW/lib/python3.9/site-packages/numpy/core/include', '/Users/akx/envs/pyFFTW/include']
clang (... as above ...) -c /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-rqqq1nam/fftwl_plan_dft.c -o /var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-rqqq1nam/fftwl_plan_dft.o

/var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/pyfftw-rqqq1nam/fftwl_plan_dft.c:2:17: error: implicit declaration of function 'fftwl_plan_dft' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                fftwl_plan_dft();
                ^
1 error generated.

Checking for fftwl_plan_dft...no
{'HAVE_DOUBLE': False, 'HAVE_DOUBLE_OMP': False, 'HAVE_DOUBLE_THREADS': False, 'HAVE_DOUBLE_MULTITHREADING': False, 'HAVE_DOUBLE_MPI': False, 'HAVE_SINGLE': False, 'HAVE_SINGLE_OMP': False, 'HAVE_SINGLE_THREADS': False, 'HAVE_SINGLE_MULTITHREADING': False, 'HAVE_SINGLE_MPI': False, 'HAVE_LONG': False, 'HAVE_LONG_OMP': False, 'HAVE_LONG_THREADS': False, 'HAVE_LONG_MULTITHREADING': False, 'HAVE_LONG_MPI': False, 'HAVE_MPI': False}
error: Could not find any of the FFTW libraries
```

# Workaround

The error can be worked around with `-Wno-error=implicit-function-declaration` in CFLAGS, so

```
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include -Wno-error=implicit-function-declaration" python setup.py -v build_ext
```

successfully builds the extension.

Similarly, to `pip install` the extension so long as no wheels exist yet (#301),

```
pip install Cython
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include -Wno-error=implicit-function-declaration" pip install pyfftw
```
does the trick.

(As an aside, if you get a problem referencing Mecab and  NLP framework and you're using DYLD_LIBRARY_PATH in your command line, try `brew unlink mecab`...)

If you need any further details, let me know, naturally 😄

**Comment by ryandesign** [comment] 2023-02-06 06:06
It's been over two years. Can you address this, please? You have to declare a function before you call it.

**Comment by hgomersall** [comment] 2023-02-06 09:59
Merge requests gratefully received.

**Comment by ryandesign** [comment] 2023-02-06 10:29
I don't know much about python and know nothing about fftw so I may not be the ideal person to help with this. I just know that you have to declare a function before you use it. It's required by C99 and later.

What is this `fftw_plan_dft` function you're using here? I assume it is part of fftw since I see some mention of it in the source code of fftw. Is it a public fftw function? I do not see a .h header provided by fftw that contains its declaration. That seems unusual to me, since the usual fix for this kind of bug is to include the header that declares the function. I do see mention of it in the fftw3.f03 file installed by fftw, but I assume that's a Fortran file that's inapplicable to this error since the error is occurring in C code.

**Comment by hgomersall** [comment] 2023-02-06 10:44
`fftw_plan_dft` is part of `FFTW` itself. It's not used by `pyFFTW`, which only uses the declarations defined in `https://github.com/pyFFTW/pyFFTW/blob/master/pyfftw/pyfftw.pxd`, using the `*plan_guru*` variants of the dft planners. I don't know what it should need a header to a function that is not used. I don't have the time at the minute to get to the bottom of this, but as I said, merge requests gratefully received (alternatively, you can pay for some of my time to deal with the problem - please contact me if you want to do this).

**Comment by akx** [comment] 2023-02-06 11:55
I think this is no longer relevant anyway since wheels are being shipped by the GitHub Actions CI process to PyPI.

**Comment by ryandesign** [comment] 2023-02-06 11:57
> I don't know why it should need a declaration to a function that is not used.

It is used by setup.py:

https://github.com/pyFFTW/pyFFTW/blob/965b82f70478e5a2586202243cd645bbb3ba15c9/setup.py#L223

`check` prepends `fftw_` to that `plan_dft` argument and sends it to `has_library`:

https://github.com/pyFFTW/pyFFTW/blob/965b82f70478e5a2586202243cd645bbb3ba15c9/setup.py#L322-L323

`has_library` calls `has_function` which writes a file called fftw_plan_dft.c into the tmp directory:

https://github.com/pyFFTW/pyFFTW/blob/965b82f70478e5a2586202243cd645bbb3ba15c9/setup.py#L404-L415

The file that's written contains:

```c
                int main() {
                fftw_plan_dft();
                return 0;
                }
```

Naturally this will elicit an implicit declaration of function warning (or error, on compilers that consider that to be an error, such as clang from Xcode 12 or later) since no declaration of the function `fftw_plan_dft` has been provided.

The issue is of course still relevant or else I would not have encountered it. Please re-open.

**Comment by akx** [comment] 2023-02-06 12:01
@ryandesign [There are binary wheels for pyfftw 0.13.1](https://pypi.org/project/pyFFTW/0.13.1/#files) for Python 3.9 on macOS, so you shouldn't ever need to try and build the library by hand.

**Comment by ryandesign** [comment] 2023-02-06 12:05
We have [pyfftw in MacPorts](https://ports.macports.org/port/py-pyfftw). MacPorts builds from source to create its own binaries and [encountered this problem](https://trac.macports.org/ticket/66543) until it was worked around by adding `-Wno-error=implicit-function-declaration` but that is a workaround; the correct fix is to declare functions before you use them.

**Comment by hgomersall** [comment] 2023-02-06 12:07
The call here: https://github.com/pyFFTW/pyFFTW/blob/965b82f70478e5a2586202243cd645bbb3ba15c9/setup.py#L223 should probably be `plan_dft_guru`.

**Comment by hgomersall** [comment] 2023-02-06 12:51
I've created #354 that should fix this. If anyone can review it, that would be great @JeppeKlitgaard @jakirkham @grlee77 ?

**Closed** 2023-02-06 15:31 UTC

**Comment by hgomersall** [comment] 2023-02-06 15:53
This should be fixed now - please confirm.
