### ISSUE TITLE
pip install pyfftw fails on travis-ci

### ISSUE THREAD

**Issue by bwohlberg** [pyFFTW/pyFFTW#125] opened 2016-06-06 14:40 UTC
The most recent release (0.10.3) of pyfftw seems to have broken building of projects using pyfftw on travis-ci: see 

https://travis-ci.org/bwohlberg/sporco/jobs/135501674

for an example of this issue. The relevant part of the build log is:

$ python --version
Python 2.7.9
$ pip --version
pip 6.0.7 from /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages (python 2.7)
$ wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
$ chmod +x miniconda.sh
$ ./miniconda.sh -b
$ export PATH=/home/travis/miniconda2/bin:$PATH
$ conda update --yes conda
$ conda install --yes nomkl
$ conda install --yes python=$TRAVIS_PYTHON_VERSION
$ conda install --yes future numpy scipy matplotlib pytest
$ pip install pyfftw
Collecting pyfftw
  Downloading pyFFTW-0.10.3.tar.gz (365kB)
    100% |████████████████████████████████| 368kB 3.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_9Iu9s/pyfftw/setup.py", line 71, in <module>
        assert tag_minor == MINOR
    AssertionError

I suspect this may be related to the recently-reported release tag format issue "Incorrectly tagged release (v10.2 instead of v0.10.2)".

**Comment by jenshnielsen** [comment] 2016-06-06 15:43
I think you can work round this by upgrading pip on travis with `pip install --upgrade pip` but there seems to be some issue with the version tag of pyFFTW


```
pip install pyFFTW --no-binary pyFFTW
Collecting pyFFTW
  Using cached pyFFTW-0.10.3.tar.gz
Collecting numpy<2.0,>=1.6 (from pyFFTW)
  Using cached numpy-1.11.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Skipping bdist_wheel for pyFFTW, due to binaries being disabled for it.
Installing collected packages: numpy, pyFFTW
  Running setup.py install for pyFFTW ... done
Successfully installed numpy-1.11.0 pyFFTW-0.10.3.dev0+e827cb5
(testing) ✔ ~ pip list
numpy (1.11.0)
pip (8.1.2)
pyFFTW (0.10.3.dev0+e827cb5)
setuptools (22.0.5)
wheel (0.29.0)
(testing) ✔ ~ pip list --outdated
pyFFTW (0.10.3.dev0+e827cb5) - Latest: 0.10.3 [sdist]
```

**Comment by hgomersall** [comment] 2016-06-06 16:20
There are various issues with the version numbers. I'm working on it and would really appreciate some help. Basically, I can't get travis to its pypi stuff properly. The encryption data is not being handled properly, not for pypi nor for the github api key.

The previous model of me having to manually set everything was pretty flaky really needed to be automated, I just keep messing it up.

**Comment by hgomersall** [comment] 2016-06-06 16:32
The problem here is that pyFFTW thinks it's being released because it inspects the relevant environment variable, but of course it's not pyFFTW being released. Any ideas on this would be much appreciated. I'm going to have to revert for the time being and look at this again.

**Comment by hgomersall** [comment] 2016-06-06 16:43
Ok, I've just made 0.10.4 release which should put everything back into a sensible state.

**Comment by hgomersall** [comment] 2016-06-06 16:52
The funny release names are still an issue. The problem is there are all manner of interacting issues, and is exactly why it needs to be sorted properly.

I can't always update the release names, because this breaks upstream packaging, so I set `version.py` to only update on non-releases when it's present. This means I can't trivially make a release from my development branch, because I've always got a `version.py` available, so I need to work with a fresh branch, which I forget to do. 

I can't use travis environment variables from inside python, because then other peoples builds also interact in strange ways. It's all a huge can of worms I've just broken.

Can you all cope for the time being with the erroneous version number?

**Comment by bwohlberg** [comment] 2016-06-06 17:02
Thanks for the very fast response. The problem is resolved for my package builds on travis-ci.

**Comment by grlee77** [comment] 2017-08-24 21:45
closing this issue as resolved.  We are now using versioneer to automate handling of the version numbers (see #176).

**Closed by grlee77** 2017-08-24 21:45 UTC
